# Generated by Django 5.2.1 on 2025-05-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saunas',
            options={'ordering': ['name'], 'verbose_name': 'Сауна', 'verbose_name_plural': 'Сауны'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
