# Generated by Django 5.2.1 on 2025-06-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_saunas_options_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaunasImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('sauna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.saunas')),
            ],
        ),
    ]
