# Generated by Django 5.2.1 on 2025-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_saunasimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saunasimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='saunas/%Y/%m/%d'),
        ),
    ]
